--BOARD 프로시저 리스트
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BOARDLIST]
	@page INT,
	@rows INT,
	@search_word nvarchar(50)
AS
	SELECT CAST(TITLE AS varchar), NAME, VIEW_CNT, REGIST_DATE FROM [dbo].[BOARD]
	ORDER BY TITLE, CONTENTS DESC
	OFFSET (@page - 1) * @rows ROWS
	FETCH NEXT @rows ROWS ONLY