CREATE TABLE TEMP(
A VARCHAR(200)NOT NULL,
B INT NOT NULL,
C DATETIME NOT NULL,
D INT NOT NULL,
E VARCHAR(10) NOT NULL,
F FLOAT NOT NULL,
G FLOAT NOT NULL,
H FLOAT NOT NULL,
I FLOAT NOT NULL,
J INT NOT NULL,
K INT NOT NULL,
L FLOAT NOT NULL,
M INT NOT NULL,
N INT,
O INT,
P INT,
Q INT,
R FLOAT NOT NULL,
S INT NOT NULL,
T INT NOT NULL,
U INT NOT NULL,
V INT NOT NULL,
W DATETIME NOT NULL
)
BULK INSERT TEMP FROM 'C:\Users\cheay\Desktop\[투비콘] 신입 개발자 교육 커리큘럼\03.임시데이터.csv'
WITH(FIRSTROW=1,KEEPNULLS, FORMAT='CSV')