DECLARE
@VIEW_CNT INT,
@INDEX INT,
@FETCH INT
SET @VIEW_CNT = 0; 
SET @INDEX = 0;

DECLARE CursorH CURSOR FOR
SELECT VIEW_CNT from BOARD 
OPEN CursorH
FETCH NEXT FROM CursorH INTO @VIEW_CNT

UPDATE CursorH
SET @VIEW_CNT=@VIEW_CNT+2

FETCH NEXT FROM CursorH INTO @VIEW_CNT